---
apiVersion: v1
kind: Secret
metadata:
  name: kms-secret
type: Opaque
data:
  key_file: MTIzNDU2
---
apiVersion: v1
kind: Secret
metadata:
  name: node0-network-secret
type: Opaque
data:
  network-key: MHg1NDQ2NmI5ZTgyMDI2ODhlN2FiYzA0ZWYzNjllNWNhMzUxODNhZTcyMjZjMWY1NGU0YzZhYjliMjZlZDVhODQ3
---
apiVersion: v1
kind: Pod
metadata:
  name: cita-cloud-single-node
spec:
  containers:
  - image: citacloud/network_p2p
    name: network
    ports:
    - containerPort: 40000
      protocol: TCP
      name: network
    - containerPort: 50000
      protocol: TCP
      name: grpc
    command:
    - sh
    - -c
    - "network run -p 50000 -k /network/network-key"
    workingDir: /data
    volumeMounts:
    - name: node0-datadir
      mountPath: /data
    - name: network-key
      mountPath: "/network"
      readOnly: true
  - image: citacloud/consensus_proof_of_sleep
    name: consensus
    ports:
    - containerPort: 50001
      protocol: TCP
      name: grpc
    command:
    - sh
    - -c
    - "consensus run -p 50001"
    workingDir: /data
    volumeMounts:
    - name: node0-datadir
      mountPath: /data
  - image: citacloud/executor_poc
    name: executor
    ports:
    - containerPort: 50002
      protocol: TCP
      name: grpc
    command:
    - sh
    - -c
    - "executor run -p 50002"
    workingDir: /data
    volumeMounts:
    - name: node0-datadir
      mountPath: /data
  - image: citacloud/storage_sqlite
    name: storage
    ports:
    - containerPort: 50003
      protocol: TCP
      name: grpc
    command:
    - sh
    - -c
    - "storage run -p 50003"
    workingDir: /data
    volumeMounts:
    - name: node0-datadir
      mountPath: /data
  - image: citacloud/controller_poc
    name: controller
    ports:
    - containerPort: 50004
      protocol: TCP
      name: grpc
    command:
    - sh
    - -c
    - "controller run -p 50004"
    workingDir: /data
    volumeMounts:
    - name: node0-datadir
      mountPath: /data
  - image: citacloud/kms
    name: kms
    ports:
    - containerPort: 50005
      protocol: TCP
      name: grpc
    command:
    - sh
    - -c
    - "kms run -p 50005 -k /kms/key_file"
    workingDir: /data
    volumeMounts:
    - name: node0-datadir
      mountPath: /data
    - name: kms-key
      mountPath: "/kms"
      readOnly: true
  volumes:
  - name: node0-datadir
    hostPath:
      path: /home/docker/cita-cloud-datadir/node0
  - name: kms-key
    secret:
      secretName: kms-secret
  - name: network-key
    secret:
      secretName: node0-network-secret
