#[[services]]
#name = "network"
#docker_image = "citacloud/network_p2p:v6.3.0"
#cmd = "network run"
[[services]]
name = "network"
docker_image = "citacloud/network_tls:v6.3.0"
cmd = "network run"
[[services]]
name = "consensus"
docker_image = "citacloud/consensus_raft:v6.3.0"
cmd = "consensus run"
#[[services]]
#name = "consensus"
#docker_image = "citacloud/consensus_bft:v6.3.0"
#cmd = "consensus run"
[[services]]
name = "executor"
docker_image = "citacloud/executor_evm:v6.3.0"
cmd = "executor run"
[[services]]
name = "storage"
docker_image = "citacloud/storage_rocksdb:v6.3.0"
cmd = "storage run"
[[services]]
name = "controller"
docker_image = "citacloud/controller:v6.3.0"
cmd = "controller run"
[[services]]
name = "kms"
docker_image = "citacloud/kms_sm:v6.3.0"
cmd = "kms run"
